server:
  port: 9999
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/spring-security-demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false

  redis:
    host: localhost
    port: 6379
    timeout: 10s

mybatis:
  type-aliases-package: com.you.springsecuritydemo.domain.entity
  mapper-locations: classpath:/mapper/**/*.xml

token:
  expire:
    seconds:  7200
    jwtSecret: (XIAO:)_$^11244^%$_(WEI:)_@@++--(LAO:)_++++_.sds_(SHI:)


